[WIP] Поиск
ivnglkv/cross_register pull request #27
Opened 2019-02-11 19:22 UTC by vessd

2019-02-14 08:35 UTC, ivnglkv requested changes

2019-02-14 08:35 UTC, ivnglkv commented on journal/views.py
> +            pbxport_set = PBXPort.objects.filter(subscriber_number = search_input)
Здесь и далее лишние пробелы в аргументах надо убрать:
https://www.python.org/dev/peps/pep-0008/#other-recommendations

2019-02-14 08:35 UTC, ivnglkv commented on journal/views.py
> +            phone_set = Phone.objects.filter(location__room__room__iregex = r'^[^0-9]*{0}[^0-9]*$'.format(search_input))
Можно заменить на
```suggestion
            phone_set = Phone.objects.filter(location__room__room__contains=search_input)
```

2019-02-14 08:35 UTC, ivnglkv commented on journal/views.py
> +            pbxport_set = PBXPort.objects.filter(main_source__in = phone_set.values('main_source'))
```suggestion
            pbxport_set = PBXPort.objects.filter(pk__in = phone_set.values('main_source'))
```

2019-02-14 08:35 UTC, ivnglkv commented on journal/views.py
> +                    path = loads(PBXPort.objects.get(main_source = phone.main_source).json_path, cls=CrosspathPointDecoder)
Слишком длинная строчка

2019-02-14 08:35 UTC, ivnglkv commented on journal/views.py
>          raise Http404
Здесь по идее 404 отдавать неправильно, надо бы это исправить. Писать что-то вроде "По вашему запросу ничего не найдено"

2019-02-14 08:35 UTC, ivnglkv commented on journal/views.py
> +                    subscriber_crosspath.setdefault(str(subscriber), []).append(path)
Использовать имя абонента в качестве ключа не надо. Что если будет два абонента с одинаковыми фамилией и инициалами?

2019-02-14 08:35 UTC, ivnglkv commented on journal/templates/journal/search.html
> +    {% for last_name, array in subscriber_crosspath.items %}
Здесь `last_name` и `array` нужно будет конечно заменить на что-то более подходящее

2019-02-14 08:35 UTC, ivnglkv commented on docker/python/dev/Dockerfile
> +    && apt-get install --no-install-recommends --no-install-suggests -y build-essential libpq-dev
Залей это отдельным PR, к поиску-то это отношения не имеет

2019-02-14 08:54 UTC, vessd commented on journal/views.py
> +            phone_set = Phone.objects.filter(location__room__room__iregex = r'^[^0-9]*{0}[^0-9]*$'.format(search_input))
Тогда при вводе "30" будут находиться комнаты 301, 302 303 и т.п.
а если ввести 1 то количество результатов будет зашкаливать

2019-02-14 09:22 UTC, ivnglkv commented on journal/templates/journal/search.html
> +{% load common_extras %}
Из `common_extras` тут ничего не используется, можно спокойно убирать

2019-02-14 09:43 UTC, ivnglkv commented on journal/views.py
> +            phone_set = Phone.objects.filter(location__room__room__iregex = r'^[^0-9]*{0}[^0-9]*$'.format(search_input))
Да, точно. Тогда лучше написать такой регэксп: `r'^.*\b{}\b.*$'`
И сделать так:
```suggestion
            room_number_pattern = r'^.*\b{}\b.*$'.format(search_input)
            phone_set = Phone.objects.filter(location__room__room__iregex=room_number_pattern)
```

2019-02-15 05:24 UTC, ivnglkv requested changes

2019-02-15 05:24 UTC, ivnglkv commented on journal/views.py
> +            room_number_pattern = r'^\D*{}\D*$'.format(search_input)
[Не всегда правильно отработает.](https://regex101.com/r/QkUxzm/2)
И `\b` тут всё-таки лучше, потому что разницы в данный момент никакой, а если потом захочется искать комнату по строке, то не нужно будет переделывать регэксп.

2019-02-15 05:24 UTC, ivnglkv commented on journal/templates/journal/search.html
> +    <h4>{{ subscriber|str }}:</h4>
Можно просто
```suggestion
    <h4>{{ subscriber }}:</h4>
```

И давай лучше `h5`. Несколько `h4`  подряд смотрятся неорганично

2019-02-15 05:24 UTC, ivnglkv commented on journal/views.py
>      search_input = request.GET.get('search_input', None)
Предлагаю 
```python3
search_input = request.GET.get('search_input', '').strip()
...
if search_input != '':
```

2019-02-15 05:24 UTC, ivnglkv commented on journal/views.py
> +                    subscriber_crosspath.setdefault(subscriber, []).extend(crosspath)
```suggestion
                    subscriber_crosspath[subscriber] = crosspath
```

2019-02-15 05:24 UTC, ivnglkv commented on journal/views.py
>  from django.urls import reverse
Надо убрать лишние импорты: `reverse`, `Http404`, `get_object_or_404`

2019-02-15 05:24 UTC, ivnglkv commented on journal/views.py
> -
Здесь функция должна отделяться двумя пустыми строками:
[https://www.python.org/dev/peps/pep-0008/#blank-lines](https://www.python.org/dev/peps/pep-0008/#blank-lines)

2019-02-15 05:24 UTC, ivnglkv commented on journal/views.py
> +                    ]
Этот паттерн часто используется, стоит его упростить

2019-02-16 05:54 UTC, ivnglkv approved these changes

2019-02-16 05:54 UTC, ivnglkv commented on journal/utils.py
> +def pbxport_to_crosspath(source):
Приму, так как буду переписывать этот кусок всё равно. Но вообще я думаю, что тут плохой дизайн функции:

- она возвращает два типа результата в зависимости от типа аргумента;
- название неточно отражает выполняемые действия и получаемый результат.

Можно переделать с помощью [дженериков](https://www.python.org/dev/peps/pep-0443/), можно разбить на две функции. Скорее даже второй вариант, потому что с первым получится то же самое что сейчас, только в профиль.

Да, у меня выше так и было сделано, но это плохо, не надо так. Там вообще муть какая-то: `get_crosspath` хоть и принимает и итерируемые, и обычные объекты, везде используется только в виде `get_crosspath(self.pk)`. С итерируемым объектом вообще зависает.

И у меня есть подозрение, что `get_crosspath` в её текущей реализации не очень-то и нужна и может быть заменена этой функцией, которую ты написал.

2019-02-16 05:54 UTC, ivnglkv commented on journal/views.py
> +    if search_input != "":
```suggestion
    if search_input != '':
```

2019-02-16 05:58 UTC, merged

2019-02-16 06:56 UTC, vessd commented on journal/utils.py
> +def pbxport_to_crosspath(source):
Да, я с делал по аналогии с твоей, поскольку не понял как лучше.

2019-02-16 06:58 UTC, vessd commented on journal/views.py
> +    if search_input != "":
Я как-то привык, что "" - это пустая строка, а '' - это символ. Опять же не знаю как это работает в питоне. Я после strip нескольких пробелов ожидаю пустую строку, которая в общем-то не равна символу.

2019-02-16 08:47 UTC, ivnglkv commented on journal/views.py
> +    if search_input != "":
`''` — это две одинарные кавычки